apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    helm:
      valueFiles:
        - app_nginx_values.yaml
    path: helm
    repoURL: https://github.com/ereanha/argocd_nginx_app.git
    targetRevision: main
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
